# Required g2o components for the native TEB optimizer.
find_path(G2O_INCLUDE_DIR g2o/core/sparse_optimizer.h REQUIRED)
set(G2O_LIBRARIES)
foreach(component core stuff solver_csparse csparse_extension solver_cholmod)
  string(TOUPPER "${component}" component_key)
  find_library(G2O_${component_key}_LIBRARY NAMES g2o_${component} REQUIRED)
  list(APPEND G2O_LIBRARIES "${G2O_${component_key}_LIBRARY}")
endforeach()
include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(G2O REQUIRED_VARS G2O_INCLUDE_DIR G2O_LIBRARIES)
